# Generated by Django 6.0.5 on 2026-06-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_medico_usuario_message_leido_profile_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='anos_experiencia',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='hospital',
        ),
        migrations.AddField(
            model_name='medico',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='licencia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medico',
            name='perfil_completado',
            field=models.BooleanField(default=False),
        ),
    ]
