# Generated by Django 6.0.5 on 2026-06-23 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_remove_medico_anos_experiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_consulta', 'En Consulta'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20),
        ),
        migrations.CreateModel(
            name='NotaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(blank=True)),
                ('tratamiento', models.TextField(blank=True)),
                ('receta', models.TextField(blank=True)),
                ('requiere_seguimiento', models.BooleanField(default=False)),
                ('fecha_seguimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota', to='citas.cita')),
            ],
        ),
        migrations.CreateModel(
            name='DiaBlockeado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=150)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_bloqueados', to='citas.medico')),
            ],
            options={
                'unique_together': {('medico', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='HorarioMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado')])),
                ('hora_inicio_manana', models.TimeField(blank=True, null=True)),
                ('hora_fin_manana', models.TimeField(blank=True, null=True)),
                ('hora_inicio_tarde', models.TimeField(blank=True, null=True)),
                ('hora_fin_tarde', models.TimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='citas.medico')),
            ],
            options={
                'unique_together': {('medico', 'dia_semana')},
            },
        ),
    ]
